// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uldclancptnevrpbhtpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsZGNsYW5jcHRuZXZycGJodHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwOTMyMTcsImV4cCI6MjA2MjY2OTIxN30.UW_hV93FFDFncX2iHU7f8_KtVOY_uKmxWAU0lSCiCdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);